// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhotosDataBase.Model;

namespace PhotosDataBase.Migrations
{
    [DbContext(typeof(PhotosDbContext))]
    [Migration("20190304165336_NewModel")]
    partial class NewModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PhotosDataBase.Model.ImportExceptionInfo", b =>
                {
                    b.Property<int>("ImportExceptionInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExceptionDateTime");

                    b.Property<string>("FileName");

                    b.Property<string>("FileNameFull");

                    b.Property<int>("ImportedDirectoryId");

                    b.Property<string>("Message");

                    b.Property<string>("StackTrace");

                    b.HasKey("ImportExceptionInfoId");

                    b.HasIndex("ImportedDirectoryId");

                    b.ToTable("ImportExceptionInfo");
                });

            modelBuilder.Entity("PhotosDataBase.Model.ImportedDirectory", b =>
                {
                    b.Property<int>("ImportedDirectoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DirectoryPath");

                    b.Property<DateTime>("ImportFinish");

                    b.Property<DateTime>("ImportStart");

                    b.HasKey("ImportedDirectoryId");

                    b.ToTable("ImportedDirectory");
                });

            modelBuilder.Entity("PhotosDataBase.Model.PhotoFileInfo", b =>
                {
                    b.Property<int>("PhotoFileInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddToBaseDate");

                    b.Property<string>("CameraModel");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("FileName");

                    b.Property<string>("FileNameFull");

                    b.Property<long>("FileSize");

                    b.Property<int>("Height");

                    b.Property<int>("ImportedDirectoryId");

                    b.Property<byte[]>("PhotoPreview");

                    b.Property<int>("Width");

                    b.HasKey("PhotoFileInfoId");

                    b.HasIndex("ImportedDirectoryId");

                    b.ToTable("PhotoFiles");
                });

            modelBuilder.Entity("PhotosDataBase.Model.ImportExceptionInfo", b =>
                {
                    b.HasOne("PhotosDataBase.Model.ImportedDirectory", "Directory")
                        .WithMany("ImportExceptions")
                        .HasForeignKey("ImportedDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhotosDataBase.Model.PhotoFileInfo", b =>
                {
                    b.HasOne("PhotosDataBase.Model.ImportedDirectory", "Directory")
                        .WithMany("Photos")
                        .HasForeignKey("ImportedDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
